const ACTION_TYPES = {


    //GETTING

    GET_CONTACTS_ACTION:'GET_CONTACTS_ACTION',
    GET_CONTACTS_REQUEST:'GET_CONTACTS_REQUEST',
    GET_CONTACTS_SUCCSESS:'GET_CONTACTS_SUCCSESS',
    GET_CONTACTS_ERROR:'GET_CONTACTS_ERROR', 

    //CREATING

    POST_CONTACT_ACTION:'POST_CONTACT_ACTION',
    POST_CONTACT_REQUEST:'POST_CONTACT_REQUEST',
    POST_CONTACT_SUCCSESS:'POST_CONTACT_SUCCSESS',
    POST_CONTACT_ERROR:'POST_CONTACT_ERROR',

    //UPDATING 

    PUT_CONTACT_ACTION:'PUT_CONTACT_ACTION',
    PUT_CONTACT_REQUEST:'PUT_CONTACT_REQUEST',
    PUT_CONTACT_SUCCSESS:'PUT_CONTACT_SUCCSESS',
    PUT_CONTACT_ERROR:'PUT_CONTACT_ERROR',

    //DELETING
    DELETE_CONTACT_ACTION:'DELETE_CONTACT_ACTION',
    DELETE_CONTACT_REQUEST:'DELETE_CONTACT_REQUEST',
    DELETE_CONTACT_SUCCSESS:'DELETE_CONTACT_SUCCSESS',
    DELETE_CONTACT_ERROR:'DELETE_CONTACT_ERROR',
}
export default ACTION_TYPES